# Generated by Django 4.1.7 on 2023-07-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='myapp.department')),
            ],
        ),
    ]
